# Generated by Django 2.2.3 on 2019-08-01 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_founded', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('year_founded', models.DateField(auto_now_add=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adress_book.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_founded', models.DateField(auto_now_add=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adress_book.City')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_founded', models.DateField(auto_now_add=True)),
                ('national_animal', models.CharField(max_length=255)),
                ('province_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adress_book.Province')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='residence_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adress_book.Residence'),
        ),
    ]
